name: Pull & update submodules

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Pages Update'
        required: true

  push:
    branches:
      - ATX-2519
      # - main
      # - develop

jobs:
  update:
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write
    #   contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: companydotcom/wave
          ref: ATX-2519
          token: ${{ secrets.SUBMOD_TOKEN }}
          submodules: recursive

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push

      # - name: Trigger Workflow and Wait
      #   uses: convictional/trigger-workflow-and-wait@v1.6.5
      #   with:
      #     owner: companydotcom
      #     repo: wave
      #     github_token: ${{ secrets.SUBMOD_TOKEN }}
      #     workflow_file_name: test.yml
      #     ref: ATX-2519

  createPullRequest:
    runs-on: ubuntu-latest
    needs: update
    env:
      BRANCH: github.event.push.base.ref

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: companydotcom/wave
          ref: ATX-2519
          token: ${{ secrets.SUBMOD_TOKEN }}
          submodules: recursive

      - name: Make changes to pull request
        run: |
          date +%s > report.txt
          echo "${{env.BRANCH}}"

      - name: Create Pull Request
        id: submod
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.SUBMOD_TOKEN }}
          commit-message: Update Submodule
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: main
          delete-branch: true
          title: '${{env.BRANCH}} | Update Submodule'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: submodule
          reviewers: ccdlt
          assignees: ccdlt
          # team-reviewers: |
          #   developers
          #   qa-team
