name: Pull & update submodules

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Pages Update'
        required: true

  push:
    branches:
      - ATX-2519
      # - main
      # - develop

jobs:
  update:
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write
    #   contents: read

    steps:
      # - name: Checkout Repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: companydotcom/wave
      #     ref: ATX-2519
      #     token: ${{ secrets.SUBMOD_TOKEN }}
      #     submodules: recursive

      - name: Trigger Test
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: companydotcom
          repo: wave
          github_token: ${{ secrets.SUBMOD_TOKEN }}
          github_user: github-user
          workflow_file_name: test.yml
          ref: ATX-2519
          client_payload: '{ submodule: pages }'

      # - name: Pull & update submodules recursively
      #   run: |
      #     git submodule update --init --recursive
      #     git submodule update --recursive --remote

      # - name: Commit
      #   run: |
      #     git config user.email "actions@github.com"
      #     git config user.name "GitHub Actions - update submodules"
      #     git add --all
      #     git commit -m "Update submodules" || echo "No changes to commit"
      #     git push
  # trigger:
  #   runs-on: u